// Sentry Error Monitoring Configuration

export const SENTRY_DSN = process.env.NEXT_PUBLIC_SENTRY_DSN || '';
export const SENTRY_ENVIRONMENT = process.env.NEXT_PUBLIC_SENTRY_ENVIRONMENT || 'development';

interface SentryConfig {
  dsn: string;
  environment: string;
  tracesSampleRate: number;
  replaysSessionSampleRate: number;
  replaysOnErrorSampleRate: number;
}

// Initialize Sentry (to be used when @sentry/nextjs is installed)
export const initSentry = () => {
  if (typeof window === 'undefined' || !SENTRY_DSN) {
    console.log('Sentry DSN not configured');
    return;
  }

  // This would be the actual Sentry initialization
  // Uncomment when @sentry/nextjs package is installed:
  /*
  import * as Sentry from '@sentry/nextjs';

  Sentry.init({
    dsn: SENTRY_DSN,
    environment: SENTRY_ENVIRONMENT,

    // Performance Monitoring
    tracesSampleRate: 1.0, // Capture 100% of transactions in development

    // Session Replay
    replaysSessionSampleRate: 0.1, // 10% of sessions
    replaysOnErrorSampleRate: 1.0, // 100% of sessions with errors

    // Additional configuration
    beforeSend(event, hint) {
      // Filter out sensitive information
      if (event.request) {
        delete event.request.cookies;
        delete event.request.headers;
      }
      return event;
    },

    // Ignore certain errors
    ignoreErrors: [
      // Browser extensions
      'top.GLOBALS',
      // Random plugins/extensions
      'originalCreateNotification',
      'canvas.contentDocument',
      'MyApp_RemoveAllHighlights',
      // Network errors
      'NetworkError',
      'Network request failed',
    ],
  });
  */

  console.log('Sentry initialized');
};

// Custom error boundary handler
export const logErrorToSentry = (error: Error, errorInfo: any) => {
  if (typeof window === 'undefined' || !SENTRY_DSN) {
    console.error('Error:', error);
    console.error('Error Info:', errorInfo);
    return;
  }

  // When Sentry is installed:
  /*
  import * as Sentry from '@sentry/nextjs';

  Sentry.captureException(error, {
    contexts: {
      react: {
        componentStack: errorInfo.componentStack,
      },
    },
  });
  */

  console.error('Error logged to Sentry:', error);
};

// Track custom events in Sentry
export const trackSentryEvent = (
  message: string,
  level: 'fatal' | 'error' | 'warning' | 'info' | 'debug' = 'info',
  extra?: Record<string, any>
) => {
  if (typeof window === 'undefined' || !SENTRY_DSN) {
    console.log(`[${level.toUpperCase()}] ${message}`, extra);
    return;
  }

  // When Sentry is installed:
  /*
  import * as Sentry from '@sentry/nextjs';

  Sentry.captureMessage(message, {
    level,
    extra,
  });
  */

  console.log(`Sentry event tracked: ${message}`);
};

// Set user context in Sentry
export const setSentryUser = (user: {
  id: string;
  email?: string;
  username?: string;
}) => {
  if (typeof window === 'undefined' || !SENTRY_DSN) return;

  // When Sentry is installed:
  /*
  import * as Sentry from '@sentry/nextjs';

  Sentry.setUser({
    id: user.id,
    email: user.email,
    username: user.username,
  });
  */

  console.log('Sentry user set:', user);
};

// Clear user context (on logout)
export const clearSentryUser = () => {
  if (typeof window === 'undefined' || !SENTRY_DSN) return;

  // When Sentry is installed:
  /*
  import * as Sentry from '@sentry/nextjs';

  Sentry.setUser(null);
  */

  console.log('Sentry user cleared');
};

// Add breadcrumb for debugging
export const addSentryBreadcrumb = (
  message: string,
  category: string,
  data?: Record<string, any>
) => {
  if (typeof window === 'undefined' || !SENTRY_DSN) return;

  // When Sentry is installed:
  /*
  import * as Sentry from '@sentry/nextjs';

  Sentry.addBreadcrumb({
    message,
    category,
    data,
    level: 'info',
  });
  */

  console.log(`Breadcrumb: [${category}] ${message}`, data);
};

// Instructions for full Sentry setup:
/*
To fully enable Sentry error monitoring:

1. Install Sentry package:
   npm install --save @sentry/nextjs

2. Run Sentry wizard:
   npx @sentry/wizard@latest -i nextjs

3. Add environment variables to .env.local:
   NEXT_PUBLIC_SENTRY_DSN=your_sentry_dsn_here
   NEXT_PUBLIC_SENTRY_ENVIRONMENT=production

4. Uncomment the Sentry initialization code in this file

5. Create sentry.client.config.ts and sentry.server.config.ts files
   (usually generated by the wizard)

6. Update next.config.ts to include Sentry webpack plugin

7. The application will automatically report errors to Sentry
*/
